services:
  # ============ KAFKA (Redpanda) ============
  redpanda-1:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.26
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '1'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda-1:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda-1:28082,OUTSIDE://localhost:8082
      - --rpc-addr
      - 0.0.0.0:33145
      - --advertise-rpc-addr
      - redpanda-1:33145
    ports:
      - 8082:8082
      - 9092:9092
      - 9644:9644
      - 28082:28082
      - 29092:29092
    networks:
      - data-network

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.2.2
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-1:29092"]
          schemaRegistry:
            enabled: false
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-1:9644"]
        connect:
          enabled: false
    ports:
      - 8081:8080
    depends_on:
      - redpanda-1
    networks:
      - data-network

  # ============ SPARK CLUSTER ============
  spark-master:
    build: .
    platform: linux/arm64
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master Port
      - "4040:4040"  # Spark Application UI
    environment:
      - SPARK_NO_DAEMONIZE=true
    networks:
      - data-network

  spark-worker:
    build: .
    platform: linux/arm64
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
    networks:
      - data-network

  spark-submit:
    build: .
    platform: linux/arm64
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker
      - redpanda-1
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./output:/opt/spark/output
      - ./data:/opt/spark/data
    networks:
      - data-network
    command: tail -f /dev/null  # Keep container running

networks:
  data-network:
    driver: bridge